# -*- coding: utf-8 -*-
"""Parcial_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CFSGtQNa-ScsPcJt-xjqI-i_dcAmE51j
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile oscilador.py
# import numpy as np
# 
# def oscilador(A, m, k, phi0, t_max, num_puntos=100):
#   w = np.sqrt(k/m)
#   t = np.linspace(0, t_max, num_puntos)
#   x = A*np.sin(w*t + phi0)
#   v = A*w*np.cos(w*t + phi0)
#   return (t, x, v)
# 
# def energia_cinetica(v, m):
#   Ek = 0.5*m*v**2
#   return Ek
# 
# def energia_potencial(x, k):
#   Ep = 0.5*k*x**2
#   return Ep
# 
# def energia_total(m, k, x, v):
#   Ek = 0.5*m*v**2
#   Ep = 0.5*k*x**2
#   E = Ek + Ep
#   return E

import numpy as np
import matplotlib.pyplot as plt
import oscilador as osc

A = 1.0       # Amplitud (m)
m = 1.0       # kg
k = 1.0       # N/m
phi0 = 0
t_max = 15.0
num_puntos = 100


w = np.sqrt(k/m)
t = np.linspace(0, t_max, num_puntos)
x = A * np.sin(w*t + phi0)
v = A * w * np.cos(w*t + phi0)

Ek = osc.energia_cinetica(v, m)
Ep = osc.energia_potencial(x, k)
Et = osc.energia_total(m, k, x, v)

fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(10, 12), sharex=True)

ax1.plot(t, x, label='Posición $x(t)$ (m)', color='blue', linewidth=2)
ax1.plot(t, v, label='Velocidad $v(t)$ (m/s)', color='red', linestyle='--', linewidth=2)
ax1.set_ylabel('Amplitud')
ax1.set_title('Oscilador Armónico')
ax1.grid(True)
ax1.legend(loc='upper right')

ax2.plot(t, Ek, label='Energía Cinética $E_k$', color='orange', linewidth=2)
ax2.plot(t, Ep, label='Energía Potencial $E_p$', color='green', linewidth=2)
ax2.set_ylabel('Energía (J)')
ax2.grid(True)
ax2.legend(loc='upper right')

ax3.plot(t, Et, label='Energía Total $E_t$', color='purple', linewidth=2.5)
ax3.set_xlabel('Tiempo (s)')
ax3.set_ylabel('Energía (J)')
ax3.set_ylim(0, max(Et) * 1.5)
ax3.grid(True)
ax3.legend(loc='upper right')

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import oscilador as osc

A = 1.0       # Amplitud (m)
m = 1.0       # kg
k = 1.0       # N/m
phi0 = 0
t_max = 15.0
num_puntos = 100

w = np.sqrt(k/m)
t = np.linspace(0, t_max, num_puntos)
x = A * np.sin(w*t + phi0)
v = A * w * np.cos(w*t + phi0)

plt.figure(figsize=(7, 7))
plt.plot(x, v, label='Trayectoria del sistema', color='purple', linewidth=2)
plt.title('Oscilador Armónico')
plt.xlabel('Posición $x(t)$ (m)')
plt.ylabel('Velocidad $v(t)$ (m/s)')
plt.axhline(0, color='black', alpha=0.5)
plt.axvline(0, color='black', alpha=0.5)
plt.grid(True)
plt.axis('equal')
plt.legend()
plt.show()