# -*- coding: utf-8 -*-
"""Tarea_Clase12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IXu58toxvQ_f3p3DtaT_E0VCQ1cBsNu
"""

import math

vi = 35      #en m/s
theta = 30   #angulo de lanzamiento
g = 9.81     #en m/s**2

theta_rad = math.radians(theta)

#Alcance de proyectil
R = vi**2 * math.sin(2*theta_rad)/g

print(f"el alcance del proyectil es de {R:-2f} metros")

#Tiempo que tarda la luz del Sol a la Tierra

d = 1.496e11       #Distancia de la Tierra al Sol
c = 2.99792458e8   #Velocidad de la luz

#Calcular tiempo
t = d/c

print(f"El tiempo que tarda la luz del Sol a la Tierra es de: {t:.2f} segundos")

print(f"El tiempo que tarda la luz del Sol a la Tierra es de: {t:.3e} segundos")